export const cityPairs: Record<string, number> = {
    "Lagos-Abuja": 1.5,
    "Lagos-Port Harcourt": 1.2,
    "Abuja-Port Harcourt": 1.3,
    "Lagos-Kano": 2.0,
    "Abuja-Kano": 1.0,
    "Lagos-Enugu": 1.4,
    "Lagos-Benin": 1.1,
    "Lagos-Owerri": 1.3,
    "Abuja-Benin": 1.2,
    "Abuja-Owerri": 1.4,
    "Port Harcourt-Kano": 1.8,
    "Port Harcourt-Enugu": 0.8,
    "Port Harcourt-Benin": 1.0,
    "Port Harcourt-Owerri": 0.7,
    "Kano-Enugu": 1.7,
    "Kano-Benin": 1.9,
    "Kano-Owerri": 2.0,
    "Enugu-Benin": 1.0,
    "Enugu-Owerri": 0.6,
    "Benin-Owerri": 0.8,
    "Lagos-Calabar": 1.4,
    "Lagos-Uyo": 1.3,
    "Lagos-Jos": 1.7,
    "Lagos-Ilorin": 1.2,
    "Lagos-Akure": 1.1,
    "Lagos-Sokoto": 2.0,
    "Lagos-Maiduguri": 2.0,
    "Lagos-Yola": 1.9,
    "Lagos-Ibadan": 1.0,
    "Lagos-Asaba": 1.2,
    "Abuja-Calabar": 1.5,
    "Abuja-Uyo": 1.4,
    "Abuja-Jos": 1.0,
    "Abuja-Ilorin": 1.1,
    "Abuja-Akure": 1.2,
    "Abuja-Sokoto": 1.8,
    "Abuja-Maiduguri": 1.7,
    "Abuja-Yola": 1.6,
    "Abuja-Ibadan": 1.3,
    "Abuja-Asaba": 1.2,
    "Port Harcourt-Calabar": 0.8,
    "Port Harcourt-Uyo": 0.7,
    "Port Harcourt-Jos": 1.6,
    "Port Harcourt-Ilorin": 1.4,
    "Port Harcourt-Akure": 1.2,
    "Port Harcourt-Sokoto": 1.9,
    "Port Harcourt-Maiduguri": 1.8,
    "Port Harcourt-Yola": 1.7,
    "Port Harcourt-Ibadan": 1.3,
    "Port Harcourt-Asaba": 1.0,
    "Kano-Calabar": 1.9,
    "Kano-Uyo": 1.8,
    "Kano-Jos": 0.9,
    "Kano-Ilorin": 1.3,
    "Kano-Akure": 1.5,
    "Kano-Sokoto": 1.0,
    "Kano-Maiduguri": 1.2,
    "Kano-Yola": 1.1,
    "Kano-Ibadan": 1.7,
    "Kano-Asaba": 1.6,
    "Enugu-Calabar": 0.9,
    "Enugu-Uyo": 0.8,
    "Enugu-Jos": 1.5,
    "Enugu-Ilorin": 1.3,
    "Enugu-Akure": 1.1,
    "Enugu-Sokoto": 1.8,
    "Enugu-Maiduguri": 1.7,
    "Enugu-Yola": 1.6,
    "Enugu-Ibadan": 1.4,
    "Enugu-Asaba": 0.9,
};

export const nigeriaCities = [
    "Lagos",
    "Abuja",
    "Port Harcourt",
    "Kano",
    "Enugu",
    "Benin",
    "Owerri",
    "Calabar",
    "Uyo",
    "Jos",
    "Ilorin",
    "Akure",
    "Sokoto",
    "Maiduguri",
    "Yola",
    "Ibadan",
    "Asaba",
    "Gombe",
    "Kaduna",
    "Makurdi",
    "Warri",
];